# Generated by Django 4.2.3 on 2023-07-18 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Reparto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('opcion1', models.IntegerField(choices=[[0, 'Retiro en Tienda'], [1, 'Reparto a domicilio']])),
                ('num_venta', models.IntegerField()),
                ('fecha_venta', models.DateField()),
                ('nombre_cli', models.CharField(max_length=60)),
                ('direccion', models.CharField(max_length=150)),
                ('telefono', models.IntegerField()),
                ('articulos', models.TextField(max_length=300)),
                ('fecha_entrega', models.DateField()),
                ('fecha_retiro', models.DateField()),
                ('opcion2', models.IntegerField(choices=[[2, 'Retiro Local'], [3, 'Retiro bodega']])),
                ('observacion', models.CharField(max_length=200)),
            ],
        ),
    ]
