# Generated by Django 4.2.3 on 2023-07-18 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reparto',
            name='fecha_entrega',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='reparto',
            name='fecha_retiro',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='reparto',
            name='fecha_venta',
            field=models.IntegerField(),
        ),
    ]
