# Generated by Django 4.2.3 on 2023-07-18 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_reparto_fecha_entrega_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reparto',
            name='fecha_entrega',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='reparto',
            name='fecha_retiro',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='reparto',
            name='fecha_venta',
            field=models.DateField(),
        ),
    ]
