# Generated by Django 4.2.3 on 2023-07-18 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_alter_reparto_fecha_entrega_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reparto',
            name='observacion',
            field=models.TextField(max_length=200),
        ),
    ]
