# Generated by Django 4.2.3 on 2023-07-18 18:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_alter_reparto_observacion'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reparto',
            old_name='articulos',
            new_name='artículos',
        ),
        migrations.RenameField(
            model_name='reparto',
            old_name='direccion',
            new_name='dirección',
        ),
        migrations.RenameField(
            model_name='reparto',
            old_name='nombre_cli',
            new_name='nombre_cliente',
        ),
        migrations.RenameField(
            model_name='reparto',
            old_name='opcion2',
            new_name='opcion_retiro',
        ),
        migrations.RenameField(
            model_name='reparto',
            old_name='opcion1',
            new_name='opción_entrega',
        ),
        migrations.RenameField(
            model_name='reparto',
            old_name='telefono',
            new_name='teléfono',
        ),
    ]
