# Generated by Django 4.2.3 on 2023-07-19 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_rename_articulos_reparto_artículos_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reparto',
            name='opcion_retiro',
            field=models.CharField(choices=[(2, 'Retiro Local'), (3, 'Retiro bodega')], max_length=1),
        ),
        migrations.AlterField(
            model_name='reparto',
            name='opción_entrega',
            field=models.CharField(choices=[(0, 'Retiro en Tienda'), (1, 'Reparto a domicilio')], max_length=1),
        ),
    ]
