# Generated by Django 4.2.3 on 2023-07-19 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_alter_reparto_opcion_retiro_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reparto',
            old_name='artículos',
            new_name='articulos',
        ),
        migrations.RenameField(
            model_name='reparto',
            old_name='dirección',
            new_name='direccion',
        ),
        migrations.RenameField(
            model_name='reparto',
            old_name='teléfono',
            new_name='telefono',
        ),
        migrations.RemoveField(
            model_name='reparto',
            name='opción_entrega',
        ),
        migrations.AddField(
            model_name='reparto',
            name='opcion_entrega',
            field=models.CharField(choices=[(0, 'Retiro en Tienda'), (1, 'Reparto a domicilio')], default='0', max_length=1),
        ),
        migrations.AlterField(
            model_name='reparto',
            name='opcion_retiro',
            field=models.CharField(choices=[(2, 'Retiro Local'), (3, 'Retiro bodega')], default='2', max_length=1),
        ),
    ]
