# Generated by Django 4.2.3 on 2023-07-21 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_rename_artículos_reparto_articulos_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reparto',
            name='opcion_entrega',
            field=models.IntegerField(choices=[(0, 'Retiro en Tienda'), (1, 'Reparto a domicilio')], default='0', max_length=1),
        ),
        migrations.AlterField(
            model_name='reparto',
            name='opcion_retiro',
            field=models.IntegerField(choices=[(2, 'Retiro Local'), (3, 'Retiro bodega')], default='2', max_length=1),
        ),
    ]
