# Generated by Django 4.2.3 on 2023-07-21 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_alter_reparto_opcion_entrega_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reparto',
            name='direccion',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='reparto',
            name='fecha_entrega',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='reparto',
            name='telefono',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
