# Generated by Django 4.2.3 on 2023-07-21 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_alter_reparto_direccion_alter_reparto_fecha_entrega_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reparto',
            name='fecha_retiro',
            field=models.DateField(blank=True, null=True),
        ),
    ]
