# Generated by Django 4.2.3 on 2023-08-02 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_alter_reparto_fecha_retiro'),
    ]

    operations = [
        migrations.AddField(
            model_name='reparto',
            name='nombre_vendedor',
            field=models.CharField(blank=True, max_length=60, null=True),
        ),
        migrations.AddField(
            model_name='reparto',
            name='num_vendedor',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
