# Generated by Django 4.2.3 on 2023-08-02 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0014_reparto_nombre_vendedor_reparto_num_vendedor'),
    ]

    operations = [
        migrations.AddField(
            model_name='reparto',
            name='entregado',
            field=models.BooleanField(default=False),
        ),
    ]
