# Generated by Django 5.2.6 on 2025-10-30 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0015_reparto_entregado'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='reparto',
            options={'ordering': ['-fecha_venta']},
        ),
        migrations.AlterField(
            model_name='reparto',
            name='direccion',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='reparto',
            name='nombre_vendedor',
            field=models.CharField(blank=True, default='', max_length=60),
        ),
        migrations.AlterField(
            model_name='reparto',
            name='observacion',
            field=models.TextField(blank=True, default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='reparto',
            name='opcion_entrega',
            field=models.IntegerField(choices=[(0, 'Retiro en Tienda'), (1, 'Reparto a domicilio')], default=0),
        ),
        migrations.AlterField(
            model_name='reparto',
            name='opcion_retiro',
            field=models.IntegerField(choices=[(2, 'Retiro Local'), (3, 'Retiro bodega')], default=2),
        ),
        migrations.AlterField(
            model_name='reparto',
            name='telefono',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
    ]
