# Generated by Django 5.2.6 on 2025-10-30 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0016_alter_reparto_options_alter_reparto_direccion_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='reparto',
            options={},
        ),
        migrations.AlterField(
            model_name='reparto',
            name='direccion',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='reparto',
            name='nombre_vendedor',
            field=models.CharField(blank=True, max_length=60, null=True),
        ),
        migrations.AlterField(
            model_name='reparto',
            name='observacion',
            field=models.TextField(max_length=200),
        ),
        migrations.AlterField(
            model_name='reparto',
            name='opcion_entrega',
            field=models.IntegerField(choices=[(0, 'Retiro en Tienda'), (1, 'Reparto a domicilio')], default='0'),
        ),
        migrations.AlterField(
            model_name='reparto',
            name='opcion_retiro',
            field=models.IntegerField(choices=[(2, 'Retiro Local'), (3, 'Retiro bodega')], default='2'),
        ),
        migrations.AlterField(
            model_name='reparto',
            name='telefono',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
